### ISSUE TITLE
compiling on SWI 9.3.13-13-g530b2d433 yields an error

### ISSUE THREAD

**Issue by Rscho314** [ridgeworks/arithmetic_types#1]
Hi!

Trying

?- Bs is transpose(ndarray([180,300,240])).

yields the following error. I had a similar error on initial compilation after installing the pack.

`ERROR: Arithmetic: `transpose(ndarray([180,300,240]))' is not a function
ERROR: In:
ERROR:   [20] throw(error(type_error(evaluable,...),_6242))
ERROR:   [17] arithmetic:expand_function(transpose(ndarray(...)),_6280,_6282) at /home/raoul/lib/swipl/library/arithmetic.pl:206
ERROR:   [16] arithmetic:math_goal_expansion(_6326 is transpose(...),_6322) at /home/raoul/lib/swipl/library/arithmetic.pl:178
ERROR:   [14] call_goal_expansion([system- ...],_6380 is transpose(...),_6360,_6362,_6364) at /home/raoul/lib/swipl/boot/expand.pl:1036
ERROR:   [13] expand_goal(_6428 is transpose(...),_6412,_6414,_6416,user,[system- ...],_6422,[]) at /home/raoul/lib/swipl/boot/expand.pl:668
ERROR:   [12] setup_call_cleanup('$expand':'$set_source_module'(user,user),'$expand':expand_goal(...,_6498,_6500,_6502,user,...,_6508,[]),'$expand':'$set_source_module'(user)) at /home/raoul/lib/swipl/boot/init.pl:682
ERROR:    [9] expand_goal(user:(_6560 is ...),_6546,user:_6568,_6550) at /home/raoul/lib/swipl/boot/expand.pl:601
ERROR:    [7] setup_call_cleanup('$toplevel':'$set_source_module'(user,user),'$toplevel':expand_goal(...,...),'$toplevel':'$set_source_module'(user)) at /home/raoul/lib/swipl/boot/init.pl:682
ERROR: 
ERROR: Note: some frames are missing due to last-call optimization.
ERROR: Re-run your program in debug mode (:- debug.) to get more detail.`

**Comment by ridgeworks** [comment]
Was pack `arithmetic types` installed? Module `type_ndarray` loaded?
```
$ /Applications/SWI-Prolog9.2.8.app/Contents/MacOS/swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.2.8)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- use_module(library(type_ndarray)).
true.

?- Bs is transpose(ndarray([180,300,240])).
Bs = #(#(180), #(300), #(240)).

?- 
```

**Comment by Rscho314** [comment]
Ok, reinstalled (again) and now it works. I guess it'll remain a mystery, but the problem is on my side. Sorry for the noise !

**Comment by ridgeworks** [comment]
I haven't used or tested `arithmetic_types` a lot so any feedback is appreciated. In particular `type_ndarry` is intended to be compatible (and uses) `clpBNR` for solving linear systems without requiring a search, but hopefully it's more useful than just that.
